### PR TITLE
Keep a reference to Sendable objects when passed to SmartDashboard::putData

### LINKED ISSUE #685: SmartDashboard::putData doesn't keep objects alive
Hi devs, @virtuald ,

Managed to isolate this issue. It's rather odd; about two-thirds of the time it provides me with an access violation, and the other third provides me with this pointer issue. Nevertheless, the issue seems to be stemming from the creation of an object within what I assume is a static function, the putData() in SmartDashboard. 

My OS is Windows 10, and my packages are up to date. My `wpilib` package is version 2021.2.2.0 and my `robotpy-commands-v2` package is version 2021.2.2.0. 

The error looks like so:
```
Traceback (most recent call last):
  File "C:\Users\Ben Bistline\AppData\Local\Programs\Python\Python39\lib\site-packages\wpilib\_impl\start.py", line 106, in start
    self.robot.startCompetition()
RuntimeError: bad_weak_ptr


Locals at innermost frame:

{ 'DriverStation': <class 'wpilib._wpilib.DriverStation'>,
  'NetworkTables': <_pyntcore._ntcore.NetworkTablesInstance object at 0x000001316C9FE670>,
  'hal': <module 'hal' from 'C:\\Users\\Ben Bistline\\AppData\\Local\\Programs\\Python\\Python39\...
  'isSimulation': True,
  'robot_cls': <class '__main__.Robot'>,
  'self': <wpilib._impl.start.RobotStarter object at 0x000001316EB0D280>,
  'wpilib': <module 'wpilib' from 'C:\\Users\\Ben Bistline\\AppData\\Local\\Programs\\Python\\Pyt...


Error at C:\Users\Ben Bistline\AppData\Local\Programs\Python\Python39\lib\site-packages\wpilib\_impl\start.py.106:start: Unhandled exception

Traceback (most recent call last):
  File "C:\Users\Ben Bistline\AppData\Local\Programs\Python\Python39\lib\site-packages\wpilib\_impl\start.py", line 106, in start
    self.robot.startCompetition()
  File "C:\Users\Ben Bistline\AppData\Local\Programs\Python\Python39\lib\site-packages\wpilib\_impl\start.py", line 106, in start
    self.robot.startCompetition()
RuntimeError: bad_weak_ptr
```
The code to replicate this issue is this: 
```
#!/usr/bin/env python3

from commands2 import TimedCommandRobot, SequentialCommandGroup, WaitCommand
from wpilib._impl.main import run
from wpilib import RobotBase, SmartDashboard

import shutil, sys

def showCommand(cmd):
    """Display the given command on the dashboard."""

    name = cmd.getName()
    name.replace("/", "_")
    SmartDashboard.putData("Commands/%s" % name, cmd)

class TestCommandGroup(SequentialCommandGroup):
    def __init__(self):
        super().__init__()
        
        cmd = WaitCommand(1)
        
        self.addCommands(
            cmd,
        )

class Robot(TimedCommandRobot):
    """Implements a Command Based robot design"""

    def robotInit(self):
        """Set up everything we need for a working robot."""
        
        self.myCommand = TestCommandGroup()
        
        showCommand(TestCommandGroup()) # Ny constructing the object in the function call, it fails.

    def teleopInit(self):
        self.myCommand.schedule()
        
    def autonomousInit(self):
        pass
   
if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "deploy":
        shutil.rmtree("opkg_cache", ignore_errors=True)
        shutil.rmtree("pip_cache", ignore_errors=True)

    run(Robot)

```
**Again, this code appears to be rather unstable and unpredictable.**

Thanks!

### PR DESCRIPTION
**Pull request by virtuald**
Fixes #685

### CODE REVIEW

File: wpilib/src/rpy/SmartDashboardData.cpp [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+void addSmartDashboardData(py::str &key, std::shared_ptr<frc::Sendable> data) {
+  auto &sdData = getSmartDashboardData();
+  sdData[key] = py::cast(data);
+}
+
+void clearSmartDashboardData() {
+  auto &sdData = getSmartDashboardData();
+  if (sdData) {
+    sdData.clear();
+    sdData.dec_ref();
```
Comment (auscompgeek) [inline wpilib/src/rpy/SmartDashboardData.cpp:27]: Is this `dec_ref` strictly necessary?

Comment (virtuald) [reply wpilib/src/rpy/SmartDashboardData.cpp:29]: Yes. Added a clarifying comment.

**Review by auscompgeek — APPROVED** [review]
lgtm!
